# Dockerfile.python-3.8
FROM my-base-image:latest
RUN apt-get update && apt-get install -y python3.8 python3.8-venv python3.8-dev \
    && ln -s /usr/bin/python3.8 /usr/local/bin/python \
    && ln -s /usr/bin/pip3 /usr/local/bin/pip
