# Dockerfile.gcc-10
FROM my-base-image:latest
RUN apt-get update && apt-get install -y gcc-10 g++-10 \
    && ln -s /usr/bin/gcc-10 /usr/local/bin/gcc \
    && ln -s /usr/bin/g++-10 /usr/local/bin/g++
