# Dockerfile.python-3.9
FROM my-base-image:latest
RUN apt-get update && apt-get install -y python3.9 python3.9-venv python3.9-dev \
    && ln -s /usr/bin/python3.9 /usr/local/bin/python \
    && ln -s /usr/bin/pip3 /usr/local/bin/pip