#cloud-config
package_update: true
package_upgrade: true
packages:
  - build-essential
  - qemu

users:
  - name: user
    gecos: My User
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users, admin
    lock_passwd: false


write_files:
  - path: /etc/netplan/50-cloud-init.yaml
    content: |
      network:
        version: 2
        ethernets:
          eth0:
            dhcp4: true

runcmd:
  - echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/user
  - chmod 440 /etc/sudoers.d/user

